const APPLICATION_URL = {
  LOGIN: '/login',
  CREATE_PASSWORD: '/create-password',
  RESET_PASSWORD: '/reset-password',
  // ========== Global USERS Routes =========
  SUPERADMIN: '/superAdmin',
  SUPERADMIN_DASHBOARD: '/superAdmin/dashboard',
  SUPERADMIN_MASTER: '/superAdmin/master',
  SUPERADMIN_LIST: '/superAdmin/adminList',
  SUPERADMIN_TUTOR_LIST: '/superAdmin/tutorList',
  SUPERADMIN_STUDENT_LIST: '/superAdmin/studentList',
  SUPERADMIN_SCHOOL_LIST: '/superAdmin/schoolList',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_MASTER: '/admin/master',
  ADMIN_LIST: '/admin/adminList',
  ADMIN_TUTOR_LIST: '/admin/tutorList',
  ADMIN_STUDENT_LIST: '/admin/studentList',
  ADMIN_SCHOOL_LIST: '/admin/schoolList',
  TUTOR: '/tutor',
  TUTOR_DASHBOARD: '/tutor/dashboard',
  STUDENT: '/student',
  STUDENT_DASHBOARD: '/student/dashboard',
  // =========== Local USER Routes ===========
  SCHOOLSUPERADMIN: '/schoolSuperAdmin',
  SCHOOLSUPERADMIN_DASHBOARD: '/schoolSuperAdmin/dashboard',
  SCHOOLSUPERADMIN_LIST: '/schoolSuperAdmin/adminList',
  SCHOOLSUPERADMIN_TUTOR_LIST: '/schoolSuperAdmin/tutorList',
  SCHOOLSUPERADMIN_STUDENT_LIST: '/schoolSuperAdmin/studentList',
  SCHOOLSUPERADMIN_SCHOOL_LIST: '/schoolSuperAdmin/schoolList',
  SCHOOLADMIN: '/schoolAdmin',
  SCHOOLADMIN_DASHBOARD: '/schoolAdmin/dashboard',
  SCHOOLADMIN_LIST: '/schoolAdmin/adminList',
  SCHOOLADMIN_TUTOR_LIST: '/schoolAdmin/tutorList',
  SCHOOLADMIN_STUDENT_LIST: '/schoolAdmin/studentList',
  SCHOOLADMIN_SCHOOL_LIST: '/schoolAdmin/schoolList',
  SCHOOLTUTOR: '/schoolTutor',
  SCHOOLTUTOR_DASHBOARD: '/schoolTutor/dashboard',
  SCHOOLSTUDENT: '/schoolStudent',
  SCHOOLSTUDENT_DASHBOARD: '/schoolStudent/dashboard',
};

export { APPLICATION_URL };
